/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import databases.db;
import databases.gajigurudb;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author werkudoro
 */
public class GajiGuru extends javax.swing.JFrame {

    DefaultTableModel tabmode;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    gajigurudb gdb = new gajigurudb();
    db db = new db();

    /**
     * Creates new form GajiGuru
     */
    public GajiGuru() {
        initComponents();
        tabelGajiGuru();
        tgl.setDateFormatString("yyyy-MM-dd");
        try {
            ResultSet idpem = gdb.GajiGuruId();
            if (idpem.next()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("GG00" + ids2));
            } else if (idpem.last()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("GG00" + ids2));
            } else {
                trx.setText("GG001");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void tabelGajiGuru() {
        Object[] baris = {"Id", "ID Guru", "Nama Guru", "Tanggal", "Jam Pelajaran", "Gaji/jam", "Tunjangan", "Keterangan Tunjangan", "total"};
        tabmode = new DefaultTableModel(null, baris);
        tblgg.setModel(tabmode);
        try {
            ResultSet gg = gdb.tabelGajiGuru();
            while (gg.next()) {
                String cid = gg.getString("costumID");
                int ig = gg.getInt("id_guru");
                String ng = gg.getString("nama_guru");
                String tgll = gg.getString("tanggal");
                int jampel = gg.getInt("jam_pelajaran");
                double gj = gg.getDouble("gaji_jam");
                double tun = gg.getDouble("tunjangan");
                String kettun = gg.getString("ket_tunjangan");
                int tot = gg.getInt("total");
                Object[] data = {cid, ig, ng, tgll, jampel, gj, tun, kettun, tot};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    public void total() {
        int a = Integer.parseInt(jampelajaran.getText());
        double b = Double.parseDouble(gajijam.getText());
        double c = Double.parseDouble(tunjangan.getText());
        if (gajijam.getText().isEmpty() && tunjangan.getText().isEmpty()) {
            total.setText(String.valueOf(a));
        } else if (tunjangan.getText().isEmpty()) {
//            double z = a * b;
            total.setText(String.valueOf(a * b));
        } else {
//            double z = a * b + c;
            total.setText(String.valueOf(a * b + c));
        }
//        double z = a * b + c;
//        total.setText(String.valueOf(z));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgg = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        trx = new javax.swing.JTextField();
        idguru = new javax.swing.JTextField();
        namaguru = new javax.swing.JTextField();
        gajijam = new javax.swing.JTextField();
        tcari = new javax.swing.JTextField();
        tunjangan = new javax.swing.JTextField();
        jampelajaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kettunjangan = new javax.swing.JTextArea();
        showguru = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 37, 53));

        tblgg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblggMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgg);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No.Transaksi");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Guru");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Jam Pelajaran Per Bulan");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gaji / Jam");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tunjangan");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("keterangan Tunjangan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Gaji : ");

        jPanel2.setBackground(new java.awt.Color(59, 137, 172));
        jPanel2.setPreferredSize(new java.awt.Dimension(498, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 210, 217));
        jLabel1.setText("Gaji Guru");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(500, 500, 500))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        cari.setBackground(new java.awt.Color(191, 210, 217));
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(191, 210, 217));
        save.setForeground(new java.awt.Color(0, 37, 53));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(191, 210, 217));
        edit.setForeground(new java.awt.Color(0, 37, 53));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(191, 210, 217));
        delete.setForeground(new java.awt.Color(0, 37, 53));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(191, 210, 217));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(191, 210, 217));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        trx.setBackground(new java.awt.Color(0, 56, 81));
        trx.setForeground(new java.awt.Color(255, 255, 255));
        trx.setCaretColor(new java.awt.Color(255, 255, 255));

        idguru.setBackground(new java.awt.Color(0, 56, 81));
        idguru.setForeground(new java.awt.Color(255, 255, 255));
        idguru.setCaretColor(new java.awt.Color(255, 255, 255));
        idguru.setEnabled(false);

        namaguru.setBackground(new java.awt.Color(0, 56, 81));
        namaguru.setForeground(new java.awt.Color(255, 255, 255));
        namaguru.setCaretColor(new java.awt.Color(255, 255, 255));
        namaguru.setEnabled(false);

        gajijam.setBackground(new java.awt.Color(0, 56, 81));
        gajijam.setForeground(new java.awt.Color(255, 255, 255));
        gajijam.setCaretColor(new java.awt.Color(255, 255, 255));
        gajijam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gajijamKeyReleased(evt);
            }
        });

        tcari.setBackground(new java.awt.Color(0, 56, 81));
        tcari.setForeground(new java.awt.Color(255, 255, 255));
        tcari.setCaretColor(new java.awt.Color(255, 255, 255));
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });

        tunjangan.setBackground(new java.awt.Color(0, 56, 81));
        tunjangan.setForeground(new java.awt.Color(255, 255, 255));
        tunjangan.setCaretColor(new java.awt.Color(255, 255, 255));
        tunjangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tunjanganKeyReleased(evt);
            }
        });

        jampelajaran.setBackground(new java.awt.Color(0, 56, 81));
        jampelajaran.setForeground(new java.awt.Color(255, 255, 255));
        jampelajaran.setCaretColor(new java.awt.Color(255, 255, 255));
        jampelajaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jampelajaranKeyReleased(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama Guru");

        print.setBackground(new java.awt.Color(191, 210, 217));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("0");
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });

        kettunjangan.setBackground(new java.awt.Color(0, 56, 81));
        kettunjangan.setColumns(20);
        kettunjangan.setForeground(new java.awt.Color(255, 255, 255));
        kettunjangan.setRows(5);
        jScrollPane2.setViewportView(kettunjangan);

        showguru.setText("+");
        showguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showguruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jampelajaran)
                    .addComponent(gajijam)
                    .addComponent(tunjangan)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(trx)
                    .addComponent(namaguru)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idguru, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showguru, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idguru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showguru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaguru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jampelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gajijam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            gdb.updateGajiGuru(format.format(tgl.getDate()), Integer.parseInt(jampelajaran.getText()), Double.parseDouble(gajijam.getText()), Double.parseDouble(tunjangan.getText()), kettunjangan.getText(),Double.parseDouble(total.getText()), namaguru.getText());
            JOptionPane.showMessageDialog(null,"Berhasil Edit Gaji Guru");
            tabelGajiGuru();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Gagal Edit Gaji Guru"+e.getMessage());
        }
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet idpem = gdb.GajiGuruId();
            if (idpem.next()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("GG00" + ids2));
            } else if (idpem.last()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("GG00" + ids2));
            } else {
                trx.setText("GG001");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        idguru.setText("");
        namaguru.setText("");
        tgl.setDate(null);
        jampelajaran.setText("");
        gajijam.setText("");
        tunjangan.setText("");
        kettunjangan.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
//            String file = "C:\\Users\\maula\\OneDrive\\Desktop\\MtsAnNizomiyah2\\src\\report\\gajiguru.jasper";
            Map<String,Object> h = new HashMap<>();
            h.put("nguru", tcari.getText());
            File nf = new File("src/report/gajiguru.jrxml");
            JasperDesign jd = JRXmlLoader.load(nf);
            JasperReport jr = (JasperReport) JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, h,db.connection());
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet cg = gdb.checkGajiGuru(namaguru.getText());
            if (cg.next()) {
                JOptionPane.showMessageDialog(null,"Data Guru sudah ada");
            } else {

                gdb.createGajiGuru(Integer.parseInt(idguru.getText()), namaguru.getText(), format.format(tgl.getDate()), Integer.parseInt(jampelajaran.getText()), Double.parseDouble(gajijam.getText()), Double.parseDouble(tunjangan.getText()), kettunjangan.getText(), Double.parseDouble(total.getText()));
                JOptionPane.showMessageDialog(null,"Data Gaji Guru berhasil dibuat");
                tabelGajiGuru();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Gaji Guru gagal dibuat"+e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void tunjanganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunjanganKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_tunjanganKeyReleased

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_totalKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            gdb.deleteGajiGuru(trx.getText());
            JOptionPane.showMessageDialog(null,"Berhasil Hapus Gaji Guru" + namaguru.getText());
            gdb.resetid();
            tabelGajiGuru();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Gagal Hapus Gaji Guru" + e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void showguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showguruActionPerformed
        // TODO add your handling code here:
        dispose();
        showGuru sg = new showGuru();
        sg.show();
    }//GEN-LAST:event_showguruActionPerformed

    private void jampelajaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jampelajaranKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_jampelajaranKeyReleased

    private void gajijamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gajijamKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_gajijamKeyReleased

    private void tblggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblggMouseClicked
        // TODO add your handling code here:
        int bar = tblgg.getSelectedRow();
        String ids = tabmode.getValueAt(bar, 0).toString();
        String idsg = tabmode.getValueAt(bar, 1).toString();
        String ng = tabmode.getValueAt(bar, 2).toString();
        try {
            java.util.Date tglgg = new SimpleDateFormat("yyyy-MM-dd").parse(tabmode.getValueAt(bar, 3).toString());
            tgl.setDate(tglgg);
        } catch (ParseException ex) {
            Logger.getLogger(datasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        String jp = tabmode.getValueAt(bar, 4).toString();
        String gj = tabmode.getValueAt(bar, 5).toString();
        String t = tabmode.getValueAt(bar, 6).toString();
        String kt = tabmode.getValueAt(bar, 7).toString();
        String to = tabmode.getValueAt(bar, 8).toString();
        trx.setText(ids);
        idguru.setText(idsg);
        namaguru.setText(ng);
        jampelajaran.setText(jp);
        gajijam.setText(gj);
        tunjangan.setText(t);
        kettunjangan.setText(kt);
        total.setText(to);
    }//GEN-LAST:event_tblggMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        Object[] baris = {"Id", "ID Guru", "Nama Guru", "Tanggal", "Jam Pelajaran", "Gaji/jam", "Tunjangan", "Keterangan Tunjangan", "total"};
        tabmode = new DefaultTableModel(null, baris);
        tblgg.setModel(tabmode);
        try {
            ResultSet gg = gdb.searchGajiGuru(tcari.getText());
            while (gg.next()) {
                String cid = gg.getString("costumID");
                int ig = gg.getInt("id_guru");
                String ng = gg.getString("nama_guru");
                String tgll = gg.getString("tanggal");
                int jampel = gg.getInt("jam_pelajaran");
                double gj = gg.getDouble("gaji_jam");
                double tun = gg.getDouble("tunjangan");
                String kettun = gg.getString("ket_tunjangan");
                int tot = gg.getInt("total");
                Object[] data = {cid, ig, ng, tgll, jampel, gj, tun, kettun, tot};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cariActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        Menu m = new Menu();
        m.show();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gajijam;
    public javax.swing.JTextField idguru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jampelajaran;
    private javax.swing.JTextArea kettunjangan;
    public javax.swing.JTextField namaguru;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JButton showguru;
    private javax.swing.JTable tblgg;
    private javax.swing.JTextField tcari;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JLabel total;
    private javax.swing.JTextField trx;
    private javax.swing.JTextField tunjangan;
    // End of variables declaration//GEN-END:variables
}
