/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import databases.db;
import databases.detaildb;
import databases.infopembayarandb;
import databases.pembayarandb;
import java.io.File;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author werkudoro
 */
public class Pembayaran extends javax.swing.JFrame {

    int bulan;
    pembayarandb pdb = new pembayarandb();
    detaildb dbd = new detaildb();
    DefaultTableModel tabmode;
    DefaultTableModel tabmode2;
    DefaultTableModel tabmode3;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    int bb;
    int x, n;
    String b;
    infopembayarandb ipdb = new infopembayarandb();
    db db = new db();

    /**
     * Creates new form PembayaranUjian
     */
    public Pembayaran() {
        initComponents();
//        tabelpemawal();
        tabelpem();
        tabelpem2();
        tglpem.setDateFormatString("yyyy-MM-dd");
        combobayar();
        try {
            DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
            ResultSet idpem = pdb.pemId();
            if (idpem.next()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("TRX00" + ids2));
            } else if (idpem.last()) {
                int ids = idpem.getInt("id");
                int ids2 = ids + 1;
                trx.setText(String.valueOf("TRX00" + ids2));
            } else {

                int l = tblpem.getRowCount();
                int ids = l + 1;
                trx.setText("TRX00" + ids);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void tabelpemawal() {
        Object[] baris = {"Id", "NISN", "Nama Siswa", "Kelas", "Jenis pembayaran", "bulan", "Nominal", "Tanggal"};
        tabmode3 = new DefaultTableModel(null, baris);
        tblpem.setModel(tabmode3);
    }

    public void tabelpem() {
        Object[] baris = {"Id", "NISN", "Nama Siswa", "Kelas", "Jenis pembayaran", "bulan", "Nominal", "Keterangan", "Tanggal"};
        tabmode = new DefaultTableModel(null, baris);
        tblpem.setModel(tabmode);
//        String a, b, c, d, f, v;
//        try {
//            ResultSet tba = ddb.tabel();
//            while (tba.next()) {
////                int a = tba.getInt("id");
//                a = tba.getString("customID");
//                b = tba.getString("NISN");
//                c = tba.getString("nama_siswa");
//                v = tba.getString("kelas");
//                d = tba.getString("jenis_pembayaran");
//                int g = tba.getInt("bulan");
//                int e = tba.getInt("nominal");
//                f = tba.getString("tanggal");
//                Object[] data = {a, b, c, v, d, g, e, f,};
//                tabmode.addRow(data);
//            }
//
//        } catch (SQLException ex) {
//            System.out.println(ex);
//        }
    }

    private void combobayar() {
        try {
            ResultSet r = ipdb.tabelpembayaran();
            while (r.next()) {
                Object[] o = new Object[1];
                o[0] = r.getString("pembayaran");
                jpcombo.addItem(o[0].toString());
            }
        } catch (Exception e) {
        }
    }

    private void tabelpem2() {
        Object[] baris = {"NISN", "Nama Siswa", "kelas", "SPP", "UTS"};
        tabmode2 = new DefaultTableModel(null, baris);
        tblpem2.setModel(tabmode2);
        String a, b, c, d, e;
        try {
            ResultSet tba = pdb.tabelpem2();
            while (tba.next()) {
                b = tba.getString("NISN");
                c = tba.getString("Nama_SIswa");
                a = tba.getString("kelas");
                bb = tba.getInt("bulan");
                e = tba.getString("SPP");
                d = tba.getString("UTS");
                Object[] data = {b, c, a, e, d};
                tabmode2.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        trx = new javax.swing.JTextField();
        nisn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpcombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tglpem = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        biayatagihan = new javax.swing.JTextField();
        jlabbulan = new javax.swing.JLabel();
        tbulan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpem = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labtb = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpem2 = new javax.swing.JTable();
        fcari2 = new javax.swing.JTextField();
        cari2 = new javax.swing.JButton();
        carinisn = new javax.swing.JButton();
        cari1 = new javax.swing.JButton();
        fcari1 = new javax.swing.JTextField();
        keterangan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tket = new javax.swing.JTextArea();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 37, 53));

        jPanel2.setBackground(new java.awt.Color(59, 137, 172));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 210, 217));
        jLabel1.setText("Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(467, 467, 467))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No.Transaksi");

        trx.setBackground(new java.awt.Color(0, 56, 81));
        trx.setForeground(new java.awt.Color(0, 56, 81));
        trx.setEnabled(false);

        nisn.setBackground(new java.awt.Color(0, 56, 81));
        nisn.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");

        nama.setBackground(new java.awt.Color(0, 56, 81));
        nama.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Pembayaran");

        jpcombo.setBackground(new java.awt.Color(0, 56, 81));
        jpcombo.setForeground(new java.awt.Color(255, 255, 255));
        jpcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pembayaran--" }));
        jpcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpcomboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kelas");

        kelas.setBackground(new java.awt.Color(0, 56, 81));
        kelas.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal");

        tglpem.setBackground(new java.awt.Color(0, 56, 81));
        tglpem.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Biaya Tagihan");

        biayatagihan.setBackground(new java.awt.Color(0, 56, 81));
        biayatagihan.setForeground(new java.awt.Color(255, 255, 255));

        jlabbulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabbulan.setForeground(new java.awt.Color(255, 255, 255));
        jlabbulan.setText("Bulan");

        tbulan.setBackground(new java.awt.Color(0, 56, 81));
        tbulan.setForeground(new java.awt.Color(255, 255, 255));
        tbulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbulanKeyReleased(evt);
            }
        });

        tblpem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblpemMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblpem);

        tambah.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        kurang.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL RP :");

        labtb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labtb.setForeground(new java.awt.Color(255, 255, 255));
        labtb.setText("0");

        save.setBackground(new java.awt.Color(191, 210, 217));
        save.setForeground(new java.awt.Color(0, 37, 53));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(191, 210, 217));
        edit.setForeground(new java.awt.Color(0, 37, 53));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(191, 210, 217));
        delete.setForeground(new java.awt.Color(0, 37, 53));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(191, 210, 217));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(191, 210, 217));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(59, 137, 172));

        tblpem2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpem2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpem2);

        cari2.setBackground(new java.awt.Color(191, 210, 217));
        cari2.setText("Cari");
        cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari2)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        carinisn.setText("+");
        carinisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carinisnActionPerformed(evt);
            }
        });

        cari1.setBackground(new java.awt.Color(191, 210, 217));
        cari1.setText("Cari");
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });

        keterangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        keterangan.setForeground(new java.awt.Color(255, 255, 255));
        keterangan.setText("Keterangan");

        tket.setBackground(new java.awt.Color(0, 56, 81));
        tket.setColumns(20);
        tket.setForeground(new java.awt.Color(255, 255, 255));
        tket.setRows(5);
        jScrollPane3.setViewportView(tket);

        print.setBackground(new java.awt.Color(191, 210, 217));
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(carinisn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(trx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jlabbulan)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(keterangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tglpem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(biayatagihan)
                                            .addComponent(jScrollPane3))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cari1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labtb)
                                .addGap(112, 112, 112)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(trx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(nisn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(carinisn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jpcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglpem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(biayatagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlabbulan)
                                .addComponent(tbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(labtb))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fcari1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(132, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int ids2, ids;
        String a, b, c, d, f, v, m;
        DefaultTableModel model = (DefaultTableModel) tblpem.getModel();

        a = trx.getText();
        b = nisn.getText();
        c = nama.getText();
        v = kelas.getText();
        d = jpcombo.getSelectedItem().toString();
        String g = tbulan.getText();
        String e = labtb.getText();
        f = format.format(tglpem.getDate());
        m = tket.getText();
        Object[] data = {a, b, c, v, d, g, e, m, f,};
        tabmode.addRow(data);
        try {
            if (b.isEmpty() || c.isEmpty()||d.isEmpty()||f.isEmpty()||e.isEmpty()||v.isEmpty()||m.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong!");
            }else{
            dbd.create(Integer.parseInt(b), c, d, Integer.parseInt(g), Integer.parseInt(e), format.format(tglpem.getDate()), v, m, a);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
//        for (int i = 0; i < model.getRowCount(); ++i) {
//            String nisnn = model.getValueAt(i, 1).toString();
//            String jp = model.getValueAt(i, 4).toString();
//            if (nisn.getText().equalsIgnoreCase(nisnn) && jpcombo.getSelectedItem().toString().equalsIgnoreCase(jp)) {
//                JOptionPane.showMessageDialog(null, "Data sudah ada");
//            } else {
//                a = trx.getText();
//                b = nisn.getText();
//                c = nama.getText();
//                v = kelas.getText();
//                d = jpcombo.getSelectedItem().toString();
//                int g = Integer.parseInt(tbulan.getText());
//                String e = labtb.getText();
//                f = format.format(tglpem.getDate());
//                Object[] data = {a, b, c, v, d, g, e, f,};
//                tabmode.addRow(data);
//            }
//        }
//        try {
//            int i = model.getRowCount();
////            for (int i = 0; i < model.getRowCount(); i++) {
//                String idss =model.getValueAt(i, 0).toString();
//                int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
//                String n = model.getValueAt(i, 2).toString();
//                String jp = model.getValueAt(i, 4).toString();
//                int bulan = Integer.parseInt(model.getValueAt(i, 5).toString());
//                int total = Integer.parseInt(model.getValueAt(i, 6).toString());
//                String ket = model.getValueAt(i, 7).toString();
//                Date date = Date.valueOf(model.getValueAt(i, 8).toString());
//                String kel = model.getValueAt(i, 3).toString();
//                dbd.create(nisnn, n, jp, bulan, total, format.format(date), kel, ket,idss); 
////            }
//        } catch (SQLException ep) {
//            System.out.println(ep);
//        }
        try {
            ResultSet idpem = pdb.pemId();
            if (idpem.next()) {
                int l = tblpem.getRowCount();
                ids = idpem.getInt("id");
                int h = ids + l + 1;
                trx.setText(String.valueOf("TRX00" + h));
            } else {
                trx.setText(String.valueOf("TRX001"));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
        model.removeRow(tblpem.getSelectedRow());
        try {
            for (int i = 0; i < model.getRowCount(); i++) {
                String ids = model.getValueAt(i, 0).toString();
                int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
                dbd.deletepem(nisnn);
            }
        } catch (Exception ep) {
            System.out.println(ep);
        }
        try {
            int l = tblpem.getRowCount();
            ResultSet idpem = pdb.pemId();
            if (idpem.next()) {
                int ids = idpem.getInt("id");
                for (int i = 1; i < l; i++) {
                    int m = i + ids + 1;
                    System.out.println(i);
                    model.setValueAt(String.valueOf("TRX00" + m), i, 0);
                }
                int h = ids + l + 1;
                trx.setText(String.valueOf("TRX00" + h));
            } else {
                int ids = idpem.getInt("id");
                int h = ids + l + 1;
                trx.setText(String.valueOf("TRX00" + h));
            }

        } catch (Exception e) {
            System.out.println(e);
        }
//        int h = l + 1;
//        System.out.println(l);
//        trx.setText(String.valueOf("TRX00" + h));
    }//GEN-LAST:event_kurangActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try {
//            ResultSet cp = pdb.checkpem(nama.getText(), jpcombo.getSelectedItem().toString());
//            if (cp.next()) {
//                String y = cp.getString("jenis_pembayaran");
//                if (!y.equalsIgnoreCase("spp")) {
//                    JOptionPane.showMessageDialog(null, "Data Pembayaran " + y + " SUdah Ada");
////                    System.out.println("Data Pembayaran "+y+" SUdah Ada");
//                } else {
//                    System.out.println("Edit sak kali");
//                }
////                System.out.println("Data SUdah Ada");
//            } 
//            else {
                DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
                    String n = model.getValueAt(i, 2).toString();
                    String jp = model.getValueAt(i, 4).toString();
                    int bulan = Integer.parseInt(model.getValueAt(i, 5).toString());
                    int total = Integer.parseInt(model.getValueAt(i, 6).toString());
                    String ket = model.getValueAt(i, 7).toString();
                    Date date = Date.valueOf(model.getValueAt(i, 8).toString());
                    String kel = model.getValueAt(i, 3).toString();
                    pdb.createpem(nisnn, n, jp, bulan, total, format.format(date), kel);

//                }
                JOptionPane.showMessageDialog(null, "Pembayaran berhasil");
                tabelpem2();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            pdb.updatepem(nisn.getText(), nama.getText(), jpcombo.getSelectedItem().toString(), Integer.parseInt(tbulan.getText()), Integer.parseInt(labtb.getText()), format.format(tglpem.getDate()), trx.getText());
            System.out.println("Data Berhasil Diupdate");
            tabelpem();
            tabelpem2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String ids = model.getValueAt(i, 0).toString();
                int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
                dbd.deletepem(nisnn);
                pdb.resetid();
            }
//            pdb.deletepem(trx.getText());
//            System.out.println("Data Berhasil Dihapus");
            pdb.resetid();
            tabelpem2();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         try {
            DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String ids = model.getValueAt(i, 0).toString();
                int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
                dbd.deletepem(nisnn);
                pdb.resetid();
            }
            pdb.resetid();
            tabelpem2();
            tabelpem();
        } catch (SQLException e) {
            System.out.println(e);
        }
        dispose();
        Menu menu = new Menu();
        menu.show();
    }//GEN-LAST:event_exitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
        nisn.setText("");
        nama.setText("");
        kelas.setText("");
        jpcombo.setSelectedIndex(0);
        biayatagihan.setText("");
        tglpem.setDate(null);
        tbulan.setText("");
        try {
            for (int i = 0; i < model.getRowCount(); i++) {
                String ids = model.getValueAt(i, 0).toString();
                int nisnn = Integer.parseInt(model.getValueAt(i, 1).toString());
                dbd.deletepem(nisnn);
                pdb.resetid();
            }
        } catch (Exception ep) {
            System.out.println(ep);
        }
        tabelpem();

        try {
            ResultSet idpem = pdb.pemId();
            if (idpem.next()) {
                int l = tblpem.getRowCount();
                int ids = idpem.getInt("id");
                int h = ids + l + 1;
                trx.setText(String.valueOf("TRX00" + h));
            } else {
                trx.setText(String.valueOf("TRX001"));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_clearActionPerformed

    private void carinisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carinisnActionPerformed
        // TODO add your handling code here:
        dispose();
        showsiswa d = new showsiswa();
        d.show();
    }//GEN-LAST:event_carinisnActionPerformed

    private void jpcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpcomboActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet dbp = pdb.getpem(jpcombo.getSelectedItem().toString());
            while (dbp.next()) {
                String jp = dbp.getString("pembayaran");
                if (jp.equalsIgnoreCase("SPP")) {
                    biayatagihan.setText(String.valueOf(dbp.getInt("nominal")));
                    tbulan.setVisible(true);
                    tambah.setVisible(true);
                    kurang.setVisible(true);
                    jlabbulan.setVisible(true);
                    keterangan.setVisible(true);
                    jScrollPane3.setVisible(true);
                    tket.setVisible(true);
                    bb = dbp.getInt("nominal");
                    tbulan.setText(String.valueOf(bulan));
                    int k = Integer.parseInt(biayatagihan.getText()) * Integer.parseInt(tbulan.getText());
                    labtb.setText(String.valueOf(k));
                } else {
                    biayatagihan.setText(String.valueOf(dbp.getInt("nominal")));
                    bb = dbp.getInt("nominal");
                    tbulan.setText(Integer.toString(0));
                    tbulan.setVisible(false);
                    tket.setVisible(false);
                    jScrollPane3.setVisible(false);
                    tambah.setVisible(true);
                    kurang.setVisible(true);
                    jlabbulan.setVisible(false);
                    keterangan.setVisible(false);
                    labtb.setText(String.valueOf(bb));
                }
//                tbt.setText(String.valueOf(dbp.getInt("nominal")));
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jpcomboActionPerformed

    private void tblpemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpemMouseClicked
        // TODO add your handling code here:
        int bar = tblpem.getSelectedRow();
        String ids = tabmode.getValueAt(bar, 0).toString();
        String nisns = tabmode.getValueAt(bar, 1).toString();
        String nsiswa = tabmode.getValueAt(bar, 2).toString();
        String kelas = tabmode.getValueAt(bar, 3).toString();
        String jp = tabmode.getValueAt(bar, 4).toString();
        n = Integer.parseInt(tabmode.getValueAt(bar, 5).toString());
        String nomm = tabmode.getValueAt(bar, 6).toString();
        String kettt = tabmode.getValueAt(bar, 7).toString();
        try {
            java.util.Date tglahir = new SimpleDateFormat("yyyy-MM-dd").parse(tabmode.getValueAt(bar, 8).toString());
            tglpem.setDate(tglahir);
        } catch (ParseException ex) {
            Logger.getLogger(datasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        trx.setText(ids);
        nisn.setText(nisns);
        nama.setText(nsiswa);
        jpcombo.setSelectedItem(jp);
        this.kelas.setText(kelas);
        biayatagihan.setText(String.valueOf(bb));
        tket.setText(kettt);
        labtb.setText(nomm);
        tbulan.setText(String.valueOf(n));
    }//GEN-LAST:event_tblpemMouseClicked

    private void tblpemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpemMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_tblpemMouseEntered

    private void cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2ActionPerformed
        // TODO add your handling code here:
        Object[] baris = {"NISN", "Nama Siswa", "SPP", "UTS"};
        tabmode2 = new DefaultTableModel(null, baris);
        tblpem2.setModel(tabmode2);
        String a, b, c, d, e;
        try {
            ResultSet tba = pdb.searchPsiswa(fcari2.getText());
            while (tba.next()) {
                b = tba.getString("NISN");
                c = tba.getString("Nama_SIswa");
                x = tba.getInt("bulan");
                e = tba.getString("SPP");
                d = tba.getString("UTS");
                Object[] data = {b, c, e, d};
                tabmode2.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_cari2ActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        // TODO add your handling code here:
        Object[] baris = {"Id", "NISN", "Nama Siswa", "Jenis pembayaran", "Nominal", "Tanggal"};
        tabmode = new DefaultTableModel(null, baris);
        tblpem.setModel(tabmode);
        String a, b, c, d, e, f;
        try {
            ResultSet tba = pdb.searchpeSiswa(fcari1.getText());
            while (tba.next()) {
//                int a = tba.getInt("id");
                a = tba.getString("costumID");
                b = tba.getString("NISN");
                c = tba.getString("nama_siswa");
                d = tba.getString("jenis_pembayaran");
                e = tba.getString("nominal");
                f = tba.getString("tanggal");
                x = tba.getInt("bulan");
                Object[] data = {a, b, c, d, e, f};
                tabmode.addRow(data);
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_cari1ActionPerformed

    private void tbulanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbulanKeyReleased
        // TODO add your handling code here:
        int k = Integer.parseInt(biayatagihan.getText()) * Integer.parseInt(tbulan.getText());
        labtb.setText(String.valueOf(k));
    }//GEN-LAST:event_tbulanKeyReleased

    private void tblpem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpem2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpem2.getModel();
        int row = tblpem2.getSelectedRow();
        int ids = Integer.parseInt(model.getValueAt(row, 0).toString());
        try {
            String a, b, c, d, f, v;
            ResultSet tba = pdb.getpem2(ids);
            while (tba.next()) {
//                int a = tba.getInt("id");
                a = tba.getString("costumID");
                b = tba.getString("NISN");
                c = tba.getString("nama_siswa");
                v = tba.getString("kelas");
                d = tba.getString("jenis_pembayaran");
                int g = tba.getInt("bulan");
                int e = tba.getInt("nominal");
                f = tba.getString("tanggal");
                Object[] data = {a, b, c, v, d, g, e, f,};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblpem2MouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) tblpem.getModel();
            Map<String, Object> h = new HashMap<String, Object>();
//            h.put("id", model.getValueAt(bar, 0));
//            h.put("nisn", model.getValueAt(bar, 1));
//            h.put("nsiswa", model.getValueAt(bar, 2));
//            h.put("kelas", model.getValueAt(bar, 3));
//            h.put("jp", model.getValueAt(bar, 4));
//            h.put("bulan", model.getValueAt(bar, 5));
//            h.put("nom", model.getValueAt(bar, 6));
//            h.put("tgl", model.getValueAt(bar, 7));

            int ni = Integer.parseInt(model.getValueAt(0, 1).toString());
            Date jps = Date.valueOf(model.getValueAt(0, 8).toString());
            System.out.println(ni);
            System.out.println(jps);
            h.put("nisn", ni);
            h.put("tanggal", format.format(jps));
            File nf = new File("src/report/detailpem.jrxml");
            JasperDesign jd = JRXmlLoader.load(nf);
            JasperReport jr = (JasperReport) JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, h, db.connection());
            JasperViewer.viewReport(jp, false);
//            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayatagihan;
    private javax.swing.JButton cari1;
    private javax.swing.JButton cari2;
    private javax.swing.JButton carinisn;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fcari1;
    private javax.swing.JTextField fcari2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabbulan;
    private javax.swing.JComboBox<String> jpcombo;
    public javax.swing.JTextField kelas;
    private javax.swing.JLabel keterangan;
    private javax.swing.JButton kurang;
    private javax.swing.JLabel labtb;
    public javax.swing.JTextField nama;
    public javax.swing.JTextField nisn;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tblpem;
    private javax.swing.JTable tblpem2;
    private javax.swing.JTextField tbulan;
    private com.toedter.calendar.JDateChooser tglpem;
    private javax.swing.JTextArea tket;
    private javax.swing.JTextField trx;
    // End of variables declaration//GEN-END:variables
}
